/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Mark;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author bmetin
 */
public class TechMark extends javax.swing.JFrame {

 
    static Connection con;
    static ResultSet rs;
    static PreparedStatement ps;
    static Statement stm;
    
    public String a;
    public TechMark() {
        initComponents();
        
        //dbConnection();
        //fillCombo();
    }
    
    
    /*
    public void fillCombo()
    {
        try {
            String sql = "SELECT * FROM STORE";
            ps=con.prepareStatement(sql);
            rs = ps.executeQuery();
            
            while(rs.next())
            {
                jComboBox4.addItem(rs.getString("STORE_ID"));
            }

            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(TechMark.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public Connection dbConnection()
    {
         try {

            Class.forName("oracle.jdbc.OracleDriver");

            System.out.println("Connection to Database...");
            con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","bm","bmlab");
            return null;
        }

        catch (Exception ex)
        {
            System.out.println("Exception: " + ex.getMessage() + "");
            return null;
        }
    }

*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("jdbc:oracle:thin:@localhost:1521:XEPU").createEntityManager();
        storeQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT s FROM Store s");
        storeList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : storeQuery.getResultList();
        storeQuery1 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT s FROM Store s");
        storeList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : storeQuery1.getResultList();
        storeQuery2 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT s FROM Store s");
        storeList2 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : storeQuery2.getResultList();
        storeQuery3 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT s FROM Store s");
        storeList3 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : storeQuery3.getResultList();
        storeQuery4 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT s FROM Store s");
        storeList4 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : storeQuery4.getResultList();
        storeQuery5 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT s FROM Store s");
        storeList5 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : storeQuery5.getResultList();
        storeQuery6 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT s FROM Store s");
        storeList6 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : storeQuery6.getResultList();
        storeQuery7 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT s FROM Store s");
        storeList7 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : storeQuery7.getResultList();
        storeQuery8 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT s FROM Store s");
        storeList8 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : storeQuery8.getResultList();
        storeQuery9 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT s FROM Store s");
        storeList9 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : storeQuery9.getResultList();
        storeQuery10 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT s FROM Store s");
        storeList10 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : storeQuery10.getResultList();
        storeQuery11 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT s FROM Store s");
        storeList11 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : storeQuery11.getResultList();
        storeQuery12 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT s FROM Store s");
        storeList12 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : storeQuery12.getResultList();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        name = new javax.swing.JPanel();
        cust_name = new javax.swing.JLabel();
        tc = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        store_id = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        num_order = new javax.swing.JLabel();
        product_id = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField7 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        order_id = new javax.swing.JLabel();
        product_id_ord = new javax.swing.JLabel();
        date_ord = new javax.swing.JLabel();
        product_name = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        address = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        ResetBut = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jComboBox4 = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1700, 1000));
        getContentPane().setLayout(null);

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 3, true));
        jPanel1.setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 3));

        jLabel1.setFont(new java.awt.Font("Algerian", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("                                        TechShowMarkt");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(20, 20, 1230, 110);

        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 2, true));
        jPanel3.setLayout(null);

        name.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 2, true));

        cust_name.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        cust_name.setForeground(new java.awt.Color(0, 153, 153));
        cust_name.setText("NAME:");

        tc.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        tc.setForeground(new java.awt.Color(0, 153, 153));
        tc.setText("TC:");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 2, true), "PRESENTATION", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Bell MT", 1, 18), new java.awt.Color(0, 153, 153))); // NOI18N

        store_id.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        store_id.setForeground(new java.awt.Color(0, 153, 153));
        store_id.setText("STORE ID:");

        date.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        date.setForeground(new java.awt.Color(0, 153, 153));
        date.setText("DATE:");

        num_order.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        num_order.setForeground(new java.awt.Color(0, 153, 153));
        num_order.setText("NUMBER of  ORDER:");

        product_id.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        product_id.setForeground(new java.awt.Color(0, 153, 153));
        product_id.setText("PRODUCT ID:");

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ANK0001", "IST0002", "IZM003", "ANT004", " " }));
        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2İtemStateChanged(evt);
            }
        });
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(product_id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(num_order, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(store_id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox5, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                    .addComponent(jTextField6)
                    .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(store_id, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(jComboBox2))
                .addGap(33, 33, 33)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(num_order, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(product_id, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(jComboBox5))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        product_id.getAccessibleContext().setAccessibleName("STOCK ID:");

        javax.swing.GroupLayout nameLayout = new javax.swing.GroupLayout(name);
        name.setLayout(nameLayout);
        nameLayout.setHorizontalGroup(
            nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nameLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nameLayout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 11, Short.MAX_VALUE))
                    .addGroup(nameLayout.createSequentialGroup()
                        .addGroup(nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tc, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cust_name, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                            .addComponent(jTextField7))))
                .addContainerGap())
        );
        nameLayout.setVerticalGroup(
            nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nameLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cust_name, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(jTextField2))
                .addGap(18, 18, 18)
                .addGroup(nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tc, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(jTextField7))
                .addGap(33, 33, 33)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(name);
        name.setBounds(27, 23, 408, 464);

        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 2, true));

        order_id.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        order_id.setForeground(new java.awt.Color(0, 153, 153));
        order_id.setText("ORDER ID:");

        product_id_ord.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        product_id_ord.setForeground(new java.awt.Color(0, 153, 153));
        product_id_ord.setText("PRODUCT ID:");

        date_ord.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        date_ord.setForeground(new java.awt.Color(0, 153, 153));
        date_ord.setText("DATE:");

        product_name.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        product_name.setForeground(new java.awt.Color(0, 153, 153));
        product_name.setText("PRODUCT NAME:");

        address.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        address.setForeground(new java.awt.Color(0, 153, 153));
        address.setText("ADDRESS:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(product_id_ord, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                            .addComponent(order_id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField8, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                            .addComponent(jTextField9))
                        .addGap(64, 64, 64)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(product_name)
                            .addComponent(date_ord, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 8, Short.MAX_VALUE)))
                .addGap(37, 37, 37))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(date_ord, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                            .addComponent(jTextField3)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField9)
                            .addComponent(order_id, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))))
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(product_name, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(product_id_ord, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(109, 109, 109))
        );

        jPanel3.add(jPanel4);
        jPanel4.setBounds(464, 23, 798, 300);

        jPanel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 2, true));

        ResetBut.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        ResetBut.setForeground(new java.awt.Color(0, 102, 102));
        ResetBut.setText("RESET");
        ResetBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetButActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 153, 153));
        jButton1.setText("INSERT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 153, 153));
        jButton2.setText("SHOW");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(ResetBut, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(jButton1)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ResetBut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel6);
        jPanel6.setBounds(453, 341, 809, 146);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\bmetin\\Pictures\\11.jpg")); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(0, 0, 1250, 500);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(26, 146, 1284, 0);

        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 3, true));
        jPanel5.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Algerian", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("PRESENTATION:");
        jPanel5.add(jLabel2);
        jLabel2.setBounds(13, 26, 280, 41);

        jLabel4.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 153));
        jLabel4.setText("DATE:");
        jPanel5.add(jLabel4);
        jLabel4.setBounds(50, 250, 161, 35);

        jLabel5.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 153));
        jLabel5.setText("STORE ID:");
        jPanel5.add(jLabel5);
        jLabel5.setBounds(50, 150, 137, 30);

        jComboBox3.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jComboBox3.setForeground(new java.awt.Color(0, 153, 153));
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01/02/2017", "21/02/2017", "03/03/2017", "15/03/2017", "23/03/2017", "10/04/2017", "15/04/2017", " " }));
        jPanel5.add(jComboBox3);
        jComboBox3.setBounds(210, 250, 220, 38);

        jLabel6.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 153));
        jLabel6.setText("NUMBER of STOCK:");
        jPanel5.add(jLabel6);
        jLabel6.setBounds(710, 160, 168, 41);

        jLabel7.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 153));
        jLabel7.setText("GUARANTEE DURATION:");
        jPanel5.add(jLabel7);
        jLabel7.setBounds(710, 260, 200, 38);

        jTextField10.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jTextField10.setForeground(new java.awt.Color(0, 153, 153));
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        jPanel5.add(jTextField10);
        jTextField10.setBounds(950, 70, 227, 41);

        jLabel8.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 153));
        jLabel8.setText("PRODUCT NAME:");
        jPanel5.add(jLabel8);
        jLabel8.setBounds(710, 70, 148, 41);

        jTextField12.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jTextField12.setForeground(new java.awt.Color(0, 153, 153));
        jPanel5.add(jTextField12);
        jTextField12.setBounds(950, 250, 227, 41);

        jTextField14.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jTextField14.setForeground(new java.awt.Color(0, 153, 153));
        jPanel5.add(jTextField14);
        jTextField14.setBounds(950, 160, 227, 41);

        jComboBox4.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jComboBox4.setForeground(new java.awt.Color(0, 153, 153));
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ANK001", "ANK002", "IST003", "IST004", "IZM005", "ANT006", "ANT007" }));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        jPanel5.add(jComboBox4);
        jComboBox4.setBounds(210, 150, 220, 38);

        jButton4.setFont(new java.awt.Font("Algerian", 0, 36)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 102, 102));
        jButton4.setText("SHOW");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton4);
        jButton4.setBounds(220, 570, 161, 49);

        jButton6.setFont(new java.awt.Font("Algerian", 0, 36)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 102, 102));
        jButton6.setText("OK");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton6);
        jButton6.setBounds(531, 180, 110, 49);

        jPanel1.add(jPanel5);
        jPanel5.setBounds(20, 150, 1230, 370);

        jButton5.setFont(new java.awt.Font("Algerian", 0, 36)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 102, 102));
        jButton5.setText("ORDER");
        jButton5.setToolTipText("");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(890, 570, 161, 49);

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\bmetin\\Desktop\\s.jpg")); // NOI18N
        jPanel1.add(jLabel10);
        jLabel10.setBounds(0, 0, 1280, 680);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 1280, 680);

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\bmetin\\Desktop\\s.jpg")); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 1290, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {

            Class.forName("oracle.jdbc.OracleDriver");

            System.out.println("Connection to Database...");
            con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","bm","bmlab");
             jTextField2.setText(jTextField2.getText());
            
         String sql = "INSERT INTO CUSTOMER (TC,NAME,ADDRESS) VALUES(124,'"+jTextField2.getText()+"','X')";
        }

        catch (Exception ex)
        {
            System.out.println("Exception: " + ex.getMessage() + "");

        }
        
        
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ResetButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetButActionPerformed
        // TODO add your handling code here:

        jTextField2.setText(null);
        //tc.setTex(null);
        store_id.setText(null);
        date.setText(null);
        num_order.setText(null);
        product_id.setText(null);
        order_id.setText(null);
        product_id_ord.setText(null);
        date_ord.setText(null);
        product_name.setText(null);
        address.setText(null);

    }//GEN-LAST:event_ResetButActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        SecondJ sJ = new SecondJ();
        
        sJ.setVisible(true);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    
    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
 
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox2İtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2İtemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2İtemStateChanged

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
  
         OrderJ order = new OrderJ(jTextField10.getText());
       
          order.setVisible(true);
       
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        try {

            Class.forName("oracle.jdbc.OracleDriver");

            System.out.println("Connection to Database...");
            Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","bm","bmlab");

            System.out.println("Creating statement");
            Statement stmt = (Statement)con.createStatement();

            jComboBox4.setName(jComboBox4.getName());
            
            String sql = "SELECT * FROM PRESENTATION";
       

            ResultSet rs = stmt.executeQuery(sql);
            String a = "MOBILE PHONE";
          if(jComboBox4.getName().equals("ANK001"))
              
             jTextField10.setName(a);

            while(rs.next())
            {

                System.out.println(rs.getInt(1) + " " + rs.getString(2));
            }

            con.close();

        }

        catch (Exception ex)
        {
            System.out.println("Exception: " + ex.getMessage() + "");

        }

           
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        
        
        /*
            ANK001
            ANK002
            IST003
            IST004
            IZM005
            ANT006
            ANT007
        */
          Object selected = jComboBox4.getSelectedItem();
         
          if(selected.toString().equals("ANK001"))
          {
                    jTextField10.setText("MOBILE PHONE");
                    jTextField14.setText("4");
                    jTextField12.setText("YES");
          }else if(selected.toString().equals("ANK002"))
          {
                    jTextField10.setText("COMPUTER");
                    jTextField14.setText("19");
                    jTextField12.setText("NO");
          }else if(selected.toString().equals("IST003"))
          {
                    jTextField10.setText("TELEVISION");
                    jTextField14.setText("200");
                    jTextField12.setText("YES");
          }
          else if(selected.toString().equals("IST004"))
          {
                    jTextField10.setText("MOUSE PAD");
                    jTextField14.setText("4");
                    jTextField12.setText("YES");
          }
           else if(selected.toString().equals("IZM005"))
          {
                    jTextField10.setText("FLASH DISK");
                    jTextField14.setText("34");
                    jTextField12.setText("NO");
            }
          
           else if(selected.toString().equals("ANT006"))
          {
                    jTextField10.setText("HARD DISK");
                    jTextField14.setText("4");
                    jTextField12.setText("NO");
            }
          
           else if(selected.toString().equals("ANT007"))
          {
                    jTextField10.setText("CD");
                    jTextField14.setText("4");
                    jTextField12.setText("YES");
            }
          
          
          
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TechMark.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TechMark.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TechMark.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TechMark.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TechMark().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ResetBut;
    private javax.swing.JLabel address;
    private javax.swing.JLabel cust_name;
    private javax.swing.JLabel date;
    private javax.swing.JLabel date_ord;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JPanel name;
    private javax.swing.JLabel num_order;
    private javax.swing.JLabel order_id;
    private javax.swing.JLabel product_id;
    private javax.swing.JLabel product_id_ord;
    private javax.swing.JLabel product_name;
    private java.util.List<Mark.Store> storeList;
    private java.util.List<Mark.Store> storeList1;
    private java.util.List<Mark.Store> storeList10;
    private java.util.List<Mark.Store> storeList11;
    private java.util.List<Mark.Store> storeList12;
    private java.util.List<Mark.Store> storeList2;
    private java.util.List<Mark.Store> storeList3;
    private java.util.List<Mark.Store> storeList4;
    private java.util.List<Mark.Store> storeList5;
    private java.util.List<Mark.Store> storeList6;
    private java.util.List<Mark.Store> storeList7;
    private java.util.List<Mark.Store> storeList8;
    private java.util.List<Mark.Store> storeList9;
    private javax.persistence.Query storeQuery;
    private javax.persistence.Query storeQuery1;
    private javax.persistence.Query storeQuery10;
    private javax.persistence.Query storeQuery11;
    private javax.persistence.Query storeQuery12;
    private javax.persistence.Query storeQuery2;
    private javax.persistence.Query storeQuery3;
    private javax.persistence.Query storeQuery4;
    private javax.persistence.Query storeQuery5;
    private javax.persistence.Query storeQuery6;
    private javax.persistence.Query storeQuery7;
    private javax.persistence.Query storeQuery8;
    private javax.persistence.Query storeQuery9;
    private javax.swing.JLabel store_id;
    private javax.swing.JLabel tc;
    // End of variables declaration//GEN-END:variables
}
